@baseUrl = http://localhost:3000

###############################################################################
# VARIABLES & HELPERS (faker-free)
###############################################################################

{{
  const orgNames = [
    "City General Hospital",
    "Green Valley Clinic",
    "Sunrise Medical Center",
    "HopeCare Health Services"
  ];

  const queueNames = [
    "Emergency Intake",
    "Pediatrics Check-in",
    "Radiology Waitlist",
    "Cardiology Priority Line",
    "Vaccination Reception"
  ];

  const consumerNames = [
    "Rahim Ahmed",
    "Nusrat Jahan",
    "Tanvir Hossain",
    "Ayesha Rahman",
    "Mehedi Hasan"
  ];

  const phones = [
    "+8801712345678",
    "+8801812345678",
    "+8801912345678"
  ];

  function pick(arr) {
    return arr[Math.floor(Math.random() * arr.length)];
  }

  exports.organizationName = pick(orgNames);
  exports.queueName = pick(queueNames);
  exports.consumerName = pick(consumerNames);
  exports.consumerPhone = pick(phones);
}}

###############################################################################
# ORGANIZATIONS
###############################################################################

### Create Organization
# @name createOrganization
POST {{baseUrl}}/organizations
Content-Type: application/json

{
  "name": "{{organizationName}}",
  "type": "business"
}

> {%
  if (!response.body.id) {
    throw new Error("Organization id missing");
  }
  client.global.set("organizationId", response.body.id);
%}

### Get Organization by ID
# @name getOrganizationById
GET {{baseUrl}}/organizations/{{organizationId}}

###############################################################################
# QUEUES
###############################################################################

### Create Queue
# @name createQueue
POST {{baseUrl}}/queues
Content-Type: application/json

{
  "organizationId": "{{organizationId}}",
  "name": "{{queueName}}"
}

> {%
  if (!response.body.id) {
    throw new Error("Queue id missing");
  }
  client.global.set("queueId", response.body.id);
%}

### Get Queue by ID
# @name getQueueById
GET {{baseUrl}}/queues/{{queueId}}

### List All Queues
# @name listQueues
GET {{baseUrl}}/queues
> {%
  if (!Array.isArray(response.body)) {
    throw new Error("Expected array of queues");
  }
%}
###############################################################################
# CONSUMERS (QUEUE-SCOPED)
###############################################################################

### Create WALK-IN Consumer (Temporary)
# @name createWalkInConsumer
POST {{baseUrl}}/queues/{{queueId}}/consumers
Content-Type: application/json

{
  "name": "{{consumerName}}",
  "phone": "{{consumerPhone}}"
}

> {%
  if (!response.body.id) {
    throw new Error("Consumer id missing");
    //console.log(response.body)
  }
  client.global.set("consumerId", response.body.id);
%}

### Get Consumer 1 by ID
# @name getConsumerById
GET {{baseUrl}}/consumers/{{consumerId}}


### Create WALK-IN Consumer 2 (Temporary)
# @name createWalkInConsumer2
POST {{baseUrl}}/queues/{{queueId}}/consumers
Content-Type: application/json

{
  "name": "{{consumerName}}",
  "phone": "{{consumerPhone}}"
}

> {%
  if (!response.body.id) {
    throw new Error("Consumer id missing");
    //console.log(response.body)
  }
  client.global.set("consumerId2", response.body.id);
%}

### Get Consumer 2 by ID
# @name getConsumer2ById
GET {{baseUrl}}/consumers/{{consumerId}}

### List Consumers for Queue
# @name listConsumersByQueue
GET {{baseUrl}}/queues/{{queueId}}/consumers

> {%
  if (!Array.isArray(response.body)) {
    throw new Error("Expected array of consumers");
  }
%}

###############################################################################
# TOKENS
###############################################################################

### Issue Token #1
POST {{baseUrl}}/queues/{{queueId}}/token
Content-Type: application/json
{
  "consumerId": "{{consumerId}}"
}

> {%
  if (!response.body.id) {
    throw new Error("Token id missing");
  }
  client.global.set("tokenId1", response.body.id);
%}
### Issue Token #2
POST {{baseUrl}}/queues/{{queueId}}/token
Content-Type: application/json
{
  "consumerId": "{{consumerId2}}"
}
# > {%
#   if (!response.body.id) {
#     throw new Error("Token id missing");
#   }
#   client.global.set("tokenId2", response.body.id);
# %}
### Call Next Token
POST {{baseUrl}}/queues/{{queueId}}/next

> {%
  if (response.body.status !== "called") {
    throw new Error("Expected token to be called");
  }
%}
